services:
  database:
    image: postgres:13-alpine
    container_name: test_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test_network

  backend:
    container_name: test_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["/src/scripts/backend-start.sh"]
    volumes:
      - .:/src
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - test_network

  redis:
    image: redis
    container_name: test_redis
    ports:
      - "6379:6379"
    networks:
      - test_network

volumes:
  postgres_data:

networks:
  test_network:
    driver: bridge
